apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: strict-galliform-nodejs 
  janus-idp.io/tekton: strict-galliform-nodejs
  backstage.io/kubernetes-id: strict-galliform-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: strict-galliform-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  